### ISSUE TITLE
The function probtorch.util.apply_poe does not exist.

### ISSUE THREAD

**Issue by antonio-t** [seqam-lab/DMVAE#2]
Hi. Thank you for sharing your code on GitHub. There is no function such as apply_poe on probtorch. I also checked the probtorch repository without success. Did you forget to add it to your code? Could you please provide it somehow? Thank you for your help.

**Comment by antonio-t** [comment]
I've tried to implement it as a multiplication of the PDF of two Gaussians represented by the input parameters.
```
def apply_poe(CUDA, sharedA_mu, sharedA_std, sharedB_mu, sharedB_std):
        mu_poe = (torch.mul(torch.square(sharedB_std), sharedA_mu) + torch.mul(torch.square(sharedA_std), sharedB_mu)) / (torch.square(sharedA_mu) + torch.square(sharedB_mu))
        std_poe = torch.sqrt(torch.mul(torch.square(sharedA_std), torch.square(sharedB_std)) / (torch.square(sharedA_std) + torch.square(sharedB_std)))
        return mu_poe, std_poe
```
It seems a Product of Experts would involve scaling the resulting PDF, but it seems the function only returns the mean and standard deviation, so I ignored the scale. Could you please confirm this procedure?

**Comment by vpellegrain** [comment]
Interested in the future answer

**Comment by seqam-lab** [comment]
Please check the updates on main.py and util.py files.
